project:
  type: website
  output-dir: docs

website:
  title: "Intro to R Course"
  
  navbar:
    background: dark        
    foreground: light
    pinned: true
    search: true
    left:
      - text: "Prepare for the course"
        href: "scripts/preparation.qmd"
      - text: "Copyright"
        href: "scripts/copyright.qmd"
      - text: "Practical Sessions"
        href: "scripts/S0_index.qmd"   
      - text: "Resources"
        href: "scripts/resources.qmd"
    tools:
      - icon: github
        menu:
          - text: "Source Code"
            url:  https://github.com/EPIET/IntroToRCourse/tree/main
          - text: "Report an issue"
            url:  https://github.com/EPIET/IntroToRCourse/issues
  

  sidebar:
  - id: sessions 
    title: "Sessions"
    style: docked
    page-navigation: true
    contents:
      - text: "Welcome"
        href: "scripts/S0_index.qmd"
      - section: "Session 1 - Basics of R"
        contents:
          - "scripts/S1E1.qmd"
          - "scripts/S1E2.qmd"
          - "scripts/S1E3.qmd"
      - section: "Session 2 - Tidyverse"
        contents:
          - "scripts/S2E1_tidy.qmd"
          - "scripts/S2E2.qmd"
          - "scripts/S2E3.qmd"
          - "scripts/S2E4.qmd"
      - section: "Session 3 - Data Cleaning"
        contents:
          - "scripts/S3E1_datacleaning.qmd"
          - "scripts/S3E2.qmd"
          - "scripts/S3E3.qmd"
          - "scripts/S3E4.qmd"
      - section: "Session 4 - Tables"
        contents:
          - "scripts/S4E1_tables.qmd"
          - "scripts/S4E2.qmd"
          - "scripts/S4E3.qmd"
          - "scripts/S4E4.qmd"
      - section: "Session 5 - ggplot2"
        contents:
          - "scripts/S5E1_ggplot.qmd"
          - "scripts/S5E2.qmd"
          - "scripts/S5E3.qmd"
          - "scripts/S5E4.qmd"
      - section: "Session 6 - Use of AI"
        contents:
          - "scripts/S6E1.qmd"
          - "scripts/S6E2.qmd"

  page-footer:
    left: "© 2026 – Intro to R Course"
    right:
      - icon: github
        href: https://github.com/EPIET/IntroToRCourse


format:
  html:
    theme: cosmo
    page-layout: full
    code-fold: false
    code-summary: "Show the code"
    code-tools: true
    code-copy: true
    toc: true
    toc-depth: 3
    toc-expand: true
    number-depth: 2
    link-external-newwindow: true
    embed-resources: false
    css: 
      - include/webex.css
    include-after-body: 
      - include/webex.js 
    page-navigation: true
    
grid:
  body-width: 1500px
  margin-width: 300px
  sidebar-width: 300px
    
execute: 
  freeze: auto
  warning: false
  message: false
  
knitr: 
  opts_chunk: 
    out.width: "100%"


editor: visual
