project:
  type: website
  output-dir: docs

website:
  title: "Intro to R Course"
  
  navbar:
    background: dark        
    foreground: light
    pinned: true
    search: true
    left:
      # - text: "---"
      #   href: "scripts/copywright.qmd"
      - text: "Copywright"
        href: "scripts/copywright.qmd"
      - text: "Practical Sessions"
        href: "scripts/S0_index.qmd"   
      - text: "Resources"
        href: "scripts/resources.qmd"
    tools:
      - icon: github
        menu:
          - text: "Source Code"
            url:  https://github.com/EPIET/IntroToRCourse/tree/main
          - text: "Report a code issue"
            url:  https://github.com/EPIET/IntroToRCourse/issues
  

  sidebar:
  - id: sessions 
    title: "Sessions"
    style: docked
    page-navigation: true
    contents:
      - text: "Welcome"
        href: "scripts/S0_index.qmd"
      - section: "Session 1"
        contents:
          - "scripts/S1E1.qmd"
          - "scripts/S1E2.qmd"
          - "scripts/S1E3.qmd"

  page-footer:
    left: "© 2026 – Intro to R Course"
    right:
      - icon: github
        href: https://github.com/EPIET/IntroToRCourse


format:
  html:
    theme: cosmo
    page-layout: full
    code-fold: true
    code-summary: "Show the code"
    code-tools: true
    code-copy: true
    toc: true
    toc-depth: 3
    toc-expand: true
    number-depth: 2
    link-external-newwindow: true
    embed-resources: true
    css: 
      - include/webex.css
    include-after-body: 
      - include/webex.js 
    
grid:
  body-width: 1500px
  margin-width: 300px
  sidebar-width: 300px
    
execute: 
  freeze: auto
  warning: false
  message: false
  
knitr: 
  opts_chunk: 
    out.width: "100%"


editor: visual
