---
title: "Copyright and License"
sidebar: false
toc: false
---

The **Intro to R Course** of the *ECDC EPIET & EUPHEM Program* was developed for the first time in 2026 to provide every starting cohort with the basics of data manipulation using the statistical software R, and RStudio

Information and documents made available on ECDC web pages are public and may be reproduced and/or distributed, totally or in part, irrespective of the means and/or the formats used, for non-commercial purposes, provided that ECDC is always acknowledged as the source of the material. Such acknowledgement must be included in each copy of the material. Any reproduction for commercial purposes will require licensing or prior permission. Citations may be made from such material without prior permission, provided the source is always acknowledged. (http://ecdc.europa.eu/en/pages/legalnotice.aspx).

**You are free:**

- **to Share** — to copy, distribute and transmit the work

- **to Remix** — to adapt the work

**Under the following conditions:**

- **Attribution** — You must attribute the work in the manner specified by the author or licensor (but not in any way that suggests that they endorse you or your use of the work). The best way to do this is to keep as it is the list of contributors: sources, authors and reviewers.

- **Share Alike** — If you alter, transform, or build upon this work, you may distribute the resulting work only under the same or similar license to this one. Your changes must be documented. Under that condition, you are allowed to add your name to the list of contributors.

You cannot sell this work alone, but you can use it as part of a teaching.

**With the understanding that:**

- **Waiver** — Any of the above conditions can be **waived** if you get permission from the copyright holder.

- **Public Domain** — Where the work or any of its elements is in the **public domain** under applicable law, that status is in no way affected by the license.

- **Other Rights** — In no way are any of the following rights affected by the license:

  - Your fair dealing or **fair use** rights, or other applicable copyright exceptions and limitations;

  - The author's **moral** rights;

  - Rights other persons may have either in the work itself or in how the work is used, such as **publicity** or privacy rights.

- **Notice** — For any reuse or distribution, you must make clear to others the license terms of this work by keeping together this work and the current license.

**This licence is based on <http://creativecommons.org/licenses/by-sa/3.0/>**

## Data source and licence

Data for this course was kindly provided by Instituto de Salud Carlos III, Spain, who coordinates with the Autonomous Regions and the Ministry of Health the Communicable Diseases Surveillance System (Sistema de Vigilancia de Enfermedades Transmisibles, SIVIET).

- The information used in this course consist on four years of surveillance data (1999-2002) of Invasive Meningococcal Disease (IMD) in four Spanish regions, that were anonymized for privacy purposes.

- Data underwent a manipulation process for "dirtying" the data, including codification mistakes, missing values, and recategorization, for pedagogical purposes.

- This data doesn't represent, and doesn't replace, official case figures and epidemiological reports. You can consult all available information (in Spanish) online in [here](https://cne.isciii.es/servicios/enfermedades-transmisibles/enfermedades-a-z/enfermedad-meningococica-invasora)
