---
title: "Tips and extras"
subtitle: "Session 1"
format:
  html:
    code-fold: false
---

```{r}
#| include: false
library(webexercises)
```

### Rstudio

## Make it yours
You'll be working a lot in Rstudio, so take some time to customise it to your liking.

You can change the appearance by going to tools -> Global options -> Appearance.

To keep track of parentheses, you can go to Tools -> Global Options -> Code -> Display and check the rainbow parentheses options. Matching parentheses will be the same colour, making your code easier to read

## The other panels

During this session, we talked about three very important panels: the console, the script and the environment. Here are a few others:

**The history panel** displays all the commands that were executed during the session.

**The file panel** shows you the directory you are currently in and allows you to navigate in your files just like file explorer.

**The plots panel** will display the plots you generate using R.

**The packages panel** shows you the list of installed packages and their version number. 

**The help panel** allows you to consult the R documentation. To look up a function, you can type its name in the search bar or type ?FunctionName in the console and press enter. Function documentation will tell you what a function does, what arguments it requires and give examples of its use. 

## Shortcuts

Shortcuts can be super helpful! 

Here are some common ones

| Shortcut           | Does            | 
|--------------------|-----------------|
| Ctrl + "Enter"     | Run (execute) selected lines   | 
| Ctrl + Shift + R   | Insert section | 

You can modify shortcuts in Tools -> Modify keyboard shortcut



